project:
  type: book
  output-dir: docs

book:
  title: "Insurance Pricing With GLMs"
  author: "Alan Chalk"
  date: "1/22/2025"
  chapters:
    - index.qmd
    - 01_preface.qmd
    - 02_getting_started.qmd
    - 03_data_preparation.qmd
    - 09_interactions.qmd
    - summary.qmd
    - references.qmd
# uncomment when we have reference in the document

bibliography: references.bib

website:
  repo-url: https://github.com/alanchalk/Insurance-Pricing-With-GLM
  
format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

editor: visual



