project:
  type: book

book:
  title: "Insurance-Pricing-With-GLMs"
  author: "Norah Jones"
  date: "1/22/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

editor: visual

